drop table USERS;

CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    USERNAME      VARCHAR(50)                             NOT NULL,
    EMAIL         VARCHAR(50)                             NOT NULL,
    USER_PASSWORD VARCHAR(200)                            NOT NULL,
    VERIFIED      BOOLEAN                                 NOT NULL,
    USER_ROLE     VARCHAR(10)                             NOT NULL,
    CONSTRAINT USER_PK PRIMARY KEY (USER_ID),
    CONSTRAINT USERNAME_UNIQUE UNIQUE (USERNAME),
    CONSTRAINT EMAIL_UNIQUE UNIQUE (EMAIL)
);