name: Java CI

on:
  push:
    branches:
      - 'develop'

#pull_request:
#  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install helper script
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y wget &&
          wget --no-check-certificate -P /tmp/ https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
          chmod a+x /tmp/wait-for-it.sh

      - name: Check and Build application
        run: |
          chmod a+x ./.github/workflows/build.sh
          ./.github/workflows/build.sh
        shell: bash

      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

      - name: Run Token Application
        run: |
          chmod a+x ./.github/workflows/runToken.sh
          ./.github/workflows/runToken.sh
        shell: bash

      #      - name: Build with Maven
      #        run: mvn --batch-mode --update-snapshots package

      - name: Waiting for Token application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:9060
          echo "Token Application is up"

      - name: Run Auth_User Application
        run: |
          chmod a+x ./.github/workflows/runUser.sh
          ./.github/workflows/runUser.sh
        shell: bash

      #      - name: Build with Maven
      #        run: mvn --batch-mode --update-snapshots package

      - name: Waiting for Auth_User application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:9070
          echo "Auth_User Application is up"

      - name: Run Auth_Client Application
        run: |
          chmod a+x ./.github/workflows/runClient.sh
          ./.github/workflows/runClient.sh
        shell: bash

      #      - name: Build with Maven
      #        run: mvn --batch-mode --update-snapshots package

      - name: Waiting for Auth_Client application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:9090
          echo "Auth_Client Application is up"

      - name: Run Resource Application
        run: |
          chmod a+x ./.github/workflows/runResource.sh
          ./.github/workflows/runResource.sh
        shell: bash

      #      - name: Build with Maven
      #        run: mvn --batch-mode --update-snapshots package

      - name: Waiting for Resource application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:9080
          echo "Resource Application is up"

      - name: Run Router Application
        run: |
          chmod a+x ./.github/workflows/runRouter.sh
          ./.github/workflows/runRouter.sh
        shell: bash

      #      - name: Build with Maven
      #        run: mvn --batch-mode --update-snapshots package

      - name: Waiting for Router application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:8080
          echo "Router Application is up"

      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "21589145-4f14ee17-fca9-4ba5-a491-e112cfa0bb38"
