name: Java CI

on:
  push:
    branches:
      - 'develop'

#pull_request:
#  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Install helper script
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y wget &&
          wget --no-check-certificate -P /tmp/ https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh &&
          chmod a+x /tmp/wait-for-it.sh

      #      - name: Build with Maven
      #        run: mvn --batch-mode --update-snapshots verify

      #      - name: Checkout tests
      #        uses: actions/checkout@v3
      #        with:
      #            repository: 'aenaumov/my-project-1'
      #            ref: ${{ github.event.pull_request.head.ref }}
      #            path: tests

      - name: Check and Build application
        run: |
          chmod a+x ./.github/workflows/build.sh
          ./.github/workflows/build.sh
        shell: bash

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Auth Application
        run: |
          chmod a+x ./.github/workflows/run.sh
          ./.github/workflows/run.sh
        shell: bash

      #      - name: Build with Maven
      #        run: mvn --batch-mode --update-snapshots package

      - name: Waiting for Auth application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:9090
          echo "Auth Application is up"

      - name: Run Resource Application
        run: |
          chmod a+x ./.github/workflows/runResource.sh
          ./.github/workflows/runResource.sh
        shell: bash

      #      - name: Build with Maven
      #        run: mvn --batch-mode --update-snapshots package

      - name: Waiting for Resource application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:9080
          echo "Resource Application is up"

      - name: Run Router Application
        run: |
          chmod a+x ./.github/workflows/runRouter.sh
          ./.github/workflows/runRouter.sh
        shell: bash

      #      - name: Build with Maven
      #        run: mvn --batch-mode --update-snapshots package

      - name: Waiting for Router application is up
        run: |
          /tmp/wait-for-it.sh -t 60 localhost:8080
          echo "Router Application is up"


      - name: Run POSTMAN tests
        run: >
          newman run ./postman/my-project-1.json
          --delay-request 50 -r cli,htmlextra
#          --verbose --color on --reporter-htmlextra-darkTheme
#          --reporter-htmlextra-export reports/myProject.html
#          --reporter-htmlextra-title "Отчет по тестам"
#          --reporter-htmlextra-logs true
#          --reporter-htmlextra-template ./tests/.github/workflows/dashboard-template.hbs